Add the visibility of net-utils-framework-common for cts-net
DnsResolverTest required DnsPacket to parse DNS answer, and the
DnsPacket class is provided by system previously.
However, DnsPacket was moved to here with changed package,
which has no backward-compatibility and might cause
NoClassDefFoundError. To solve this problem, build the DnsResolverTest with
DnsPacket directly.

Test: build
Test: atest DnsResolverTest
Bug: 150952393
(clean cherry-pick from internal branch)
Merged-In: I463fd58173cee55a210fa6c6b8c9b0d5a74b7906
Change-Id: I463fd58173cee55a210fa6c6b8c9b0d5a74b7906