Disable API level and kernel version static asserts for RISC-V.
(riscv isn't released, and thus is 10000)

Should fix:
  Broken build 13940537 on git_main-without-vendor on aosp_cf_riscv64_phone-aosp_current-userdebug

FAILED: ...
packages/modules/Connectivity/bpf/loader/NetBpfLoad.cpp:91:15: error: static assertion failed due to requirement '10000 == 30': NetBpfLoad must be compiled for 30/R
   91 | static_assert(__ANDROID_API__ == 30, "NetBpfLoad must be compiled for 30/R");
      |               ^~~~~~~~~~~~~~~~~~~~~
<built-in>:500:25: note: expanded from macro '__ANDROID_API__'
  500 | #define __ANDROID_API__ __ANDROID_MIN_SDK_VERSION__
      |                         ^
<built-in>:499:37: note: expanded from macro '__ANDROID_MIN_SDK_VERSION__'
  499 | #define __ANDROID_MIN_SDK_VERSION__ 10000
      |                                     ^
1 error generated.

Bug: 438908493
Test: TreeHugger
Flag: EXEMPT mainline & compile fix for unreleased RiscV
Signed-off-by: Maciej Żenczykowski <maze@google.com>
Change-Id: I50ba1c3159c277fb8becb68220ba0885cf30e996