Improve error message of TestableNetworkCallback#expect
Currently, expect method only use the given error message
when predicate is not matched. In some cases, it could cause
some confusions where we might just want the tester to
ensure the data subscription is valid.

Make other fail cases use the error message if provided.
This would provide more clear error message for the callers
e.g. NetworkCallbackHelper#requestCell

Exmaple output:
java.lang.AssertionError: Cell network not available. Please
ensure the device has working mobile data. : Did not receive
Available after 30000ms.

Test: Manual
Bug: N/A
Change-Id: If00c84d622a69d9b7bab7b333da9d1449ba747c2